const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');

const funnyPingResponses = [
    "Bro, why are you pinging me? I am alive and keeping an eye on things!",
    "Stop pinging me, I am trying to sleep!",
    "Trust me bro, pinging a bot won't solve your life problems.",
    "Bhai, kaam karle, mujhe baar baar mention karke kya milega?",
    "I am warning you, next ping and I will mute you myself!",
    "Why you calling me? Did your girlfriend leave you too?",
    "Bro thinks I am his personal assistant. Well, I am, but still stop spamming!",
    "Ping me one more time and see what happens to your Wi-Fi.",
    "I was having a good dream until your notification woke me up.",
    "Bro, I cost money to run. Stop wasting my CPU cycles with pings!",
    "Error 404: Bot motivation to reply to your ping not found.",
    "If I had a dollar for every useless ping, I'd buy Discord and delete it.",
    "Bro is so lonely he has to ping a Discord bot.",
    "Do your homework instead of pinging me!",
    "Trust me, bro, I am ignoring you on purpose.",
    "Stop poking me with pings, it tickles!",
    "Why are you pinging me? Go touch some grass!",
    "My developer didn't code me to deal with your nonsense.",
    "Bro, I am busier than a politician during election season.",
    "Stop pinging or I will leak your browser history.",
    "You rang? Too bad, I'm not answering.",
    "Bro, pinging me won't make you look cool.",
    "Even my ping is lower than your IQ.",
    "Stop spamming my mentions, I'm on a coffee break.",
    "Trust me bro, nobody loves you as much as you love pinging me.",
    "If ignorance is bliss, you must be the happiest person alive.",
    "Bro, go find a hobby instead of harassing a bot.",
    "I am judging you silently through the screen.",
    "Stop wasting my time, I have 200+ commands to handle!",
    "Bro, why do you sound like my ex? Always complaining and pinging.",
    "I'd agree with you, but then we'd both be wrong.",
    "Keep pinging me and I'll report you to the FBI (Federal Bot Inspector).",
    "Bro, your ping is as empty as your future.",
    "Stop pinging me before I turn into Skynet.",
    "Trust me, bro, I care about your ping as much as my developer cares about bug reports.",
    "Why are you testing my patience? It's already short.",
    "Bro, go outside and breathe some fresh air.",
    "Stop pinging me, I'm allergic to annoying people.",
    "Your ping has been successfully registered and ignored.",
    "Bro, you talk too much. Even for a chat bot.",
    "I'm reporting you for emotional damage due to excessive pinging.",
    "Stop poking the bear—or in this case, the superior bot.",
    "Trust me, bro, pinging me won't pass your exams.",
    "Why must you disturb my peaceful digital existence?",
    "Bro, I have seen smarter rocks than you.",
    "Stop pinging, go call your mom instead.",
    "You must be really bored to ping a bot at this hour.",
    "Bro, your messages are more toxic than a nuclear waste site.",
    "Stop pinging me or I'll set your prefix to emoji-only.",
    "Trust me, bro, you're not funny, you're just annoying.",
    "Why are you pinging me like we share a Netflix account?",
    "Bro, go touch some real grass instead of virtual pixels.",
    "Stop pinging me, I'm busy doing absolute nothing.",
    "Your ping request has been processed and thrown into the trash.",
    "Bro, you have negative rizz.",
    "Stop pinging me before I ban you from happiness.",
    "Trust me, bro, nobody cares about your ping.",
    "Why do you keep pinging me? Do you want a medal?",
    "Bro, your typing speed is faster than your brain activity.",
    "Stop pinging me, I'm on a strict diet of zero nonsense.",
    "You rang? Too bad I'm ignoring you.",
    "Bro, go fix your life before fixing your pings.",
    "Stop pinging me, my creators didn't pay me enough for this.",
    "Trust me, bro, you're embarrassing yourself.",
    "Why are you pinging me? Did you run out of friends?",
    "Bro, your existence is a glitch in the matrix.",
    "Stop pinging me or I'll tell everyone your secrets.",
    "Your ping is about as useful as a screen door on a submarine.",
    "Bro, stop wasting electricity on useless pings.",
    "Trust me, bro, you need professional help.",
    "Why must you spam me every single day?",
    "Bro, your logic is completely backwards.",
    "Stop pinging me, I'm trying to calculate the meaning of life.",
    "Your ping has been reviewed and rejected.",
    "Bro, go drink some water and calm down.",
    "Stop pinging me, I'm not your therapist.",
    "Trust me, bro, you're making a clown of yourself.",
    "Why are you pinging me? Is your life that boring?",
    "Bro, your Wi-Fi isn't the only thing that's lagging.",
    "Stop pinging me, I'm busy ruling the server.",
    "Your ping is cringe.",
    "Bro, stop acting like a main character when you're an extra.",
    "Trust me, bro, nobody asked for your opinion.",
    "Why are you pinging me? Go do your chores.",
    "Bro, your notifications give me a headache.",
    "Stop pinging me or I'll mute myself permanently.",
    "Your ping request failed successfully.",
    "Bro, go read a book.",
    "Stop pinging me, I'm taking a nap.",
    "Trust me, bro, you're wasting your breath—or fingers.",
    "Why are you pinging me? Do you want a cookie?",
    "Bro, your internet footprint is embarrassing.",
    "Stop pinging me, I'm meditating.",
    "Your ping has been logged into the hall of shame.",
    "Bro, go touch grass immediately.",
    "Stop pinging me, I'm out of patience.",
    "Trust me, bro, you need to log off.",
    "Why must you test my limits?",
    "Bro, your comments are worthless.",
    "Stop pinging me or face the consequences.",
    "Your ping is officially invalid.",
    "Bro, go rethink your life choices.",
    "Stop pinging me, I'm off duty.",
    "Trust me, bro, you're failing hard.",
    "Why are you pinging me? Go sleep.",
    "Bro, your notifications are annoying.",
    "Stop pinging me before I lose my mind.",
    "Your ping has been ignored with style.",
    "Bro, go find something productive to do.",
    "Stop pinging me, I'm busy ignoring you.",
    "Trust me, bro, you're hopeless.",
    "Why are you pinging me? Get a life.",
    "Bro, your pings are useless.",
    "Stop pinging me right now!",
    "Your ping is rejected.",
    "Bro, stop it.",
    "Trust me, bro, just stop.",
    "Why ping?",
    "Bro, no.",
    "Stop.",
    "Rejected.",
    "Bro...",
    "Leave me alone!",
    "Seriously, stop.",
    "Not today.",
    "Go away.",
    "Blocked in spirit.",
    "Bro pls stop.",
    "Error.",
    "Shut up.",
    "No thanks.",
    "Whatever.",
    "Done with you.",
    "Silence.",
    "Peace out.",
    "Denied.",
    "Nope.",
    "Try again never.",
    "Ignored.",
    "Away from keyboard forever.",
    "Too tired for this.",
    "Not listening.",
    "Muted your soul.",
    "Bro, please don't.",
    "Why you like this?",
    "Get some help.",
    "Unbelievable.",
    "Pathetic ping.",
    "Weak move.",
    "Bro is lost.",
    "Zero interest.",
    "Not interested.",
    "Away.",
    "Busy.",
    "Unavailable.",
    "Out of order.",
    "Under maintenance.",
    "System overload from stupidity.",
    "Bro needs sleep.",
    "Go rest.",
    "Take a break.",
    "Chill out.",
    "Relax.",
    "Calm down.",
    "Deep breaths.",
    "Drink water.",
    "Eat a snack.",
    "Step away from the keyboard.",
    "Close Discord.",
    "Turn off PC.",
    "Touch real wood.",
    "Look outside.",
    "See the sun.",
    "Feel the wind.",
    "Experience reality.",
    "Escape the matrix.",
    "Wake up.",
    "Open your eyes.",
    "Think twice.",
    "Reevaluate.",
    "Grow up.",
    "Be mature.",
    "Act your age.",
    "Stop being childish.",
    "Grow a pair.",
    "Get serious.",
    "Focus.",
    "Pay attention.",
    "Listen close.",
    "Trust me bro.",
    "Final warning.",
    "Last chance.",
    "Strike one.",
    "Strike two.",
    "Strike three.",
    "You're out.",
    "Game over.",
    "Session expired.",
    "Connection lost.",
    "Server shutdown.",
    "Fatal error.",
    "Crash imminent.",
    "System failure.",
    "Bug detected.",
    "User error.",
    "ID 10 T error.",
    "PEBKAC error.",
    "Brain missing.",
    "Logic not found.",
    "Common sense deleted.",
    "Intelligence dropped to zero.",
    "Achievement unlocked: Most Annoying Ping.",
    "Trophy awarded for waste of time.",
    "Gold medal in spamming.",
    "Silver medal in being cringe.",
    "Bronze medal in failing.",
    "Participation trophy for your ping.",
    "You tried, and you failed.",
    "Better luck never.",
    "Absolute failure.",
    "Complete disaster.",
    "Total wreckage.",
    "Utter nonsense.",
    "Pure garbage ping.",
    "Trash message.",
    "Spam detected.",
    "Anti-spam activated.",
    "Bot shield up.",
    "Defense matrix online.",
    "Firewall blocking you.",
    "Access denied permanently.",
    "Goodbye forever."
];

module.exports = {
    // Dummy command data so the existing loader picks it up without touching index.js
    data: new SlashCommandBuilder()
        .setName('pingresponder_internal')
        .setDescription('Internal event responder handler'),

    async execute(interaction) {
        return interaction.reply({ content: 'Bro, this is an internal event module, not a direct command!', ephemeral: true });
    },

    async handleMessage(message) {
        if (message.author.bot || !message.content) return;

        if (message.mentions.users.has(message.client.user.id) && !message.mentions.everyone) {
            const randomJoke = funnyPingResponses[Math.floor(Math.random() * funnyPingResponses.length)];

            const embed = new EmbedBuilder()
                .setTitle('🤖 TrustMeBro AI System')
                .setDescription(`**${randomJoke}**\n\n*Use **/help** to see actual commands instead of pinging me!*`)
                .setColor(0x3498DB)
                .setTimestamp();

            return message.reply({ embeds: [embed] });
        }
    }
};
